version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: auction_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: auction_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - auction_network

volumes:
  mongodb_data:

networks:
  auction_network:
    driver: bridge